apiVersion: apps/v1
kind: Deployment
metadata:
  name: selva-backend
  namespace: batch2
spec:
  selector:
    matchLabels:
      app: backend-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend-mysql
    spec:
      containers:
      - image: 915551958967.dkr.ecr.ap-south-1.amazonaws.com/mysql_container:selvaganeshan
        name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
