apiVersion: apps/v1
kind: Deployment
metadata:
  name: selva-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selva-jenkins
  template:
    metadata:
      labels:
        app: selva-jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: { }
